### ISSUE TITLE
[PBPR] Package Build Permission

### ISSUE THREAD

**Issue by BalalaX** [TrdHuy/DezoneOrgManager#15]
### 📧 Email Address

limjisu697@gmail.com

### 📂 Select Package

ArtWiz

### ✍️ Reason for Request

Please give me permission for this package! Thank you!

**Comment by TrdHuy** [comment]
### ✅ Your request has been processed successfully and is awaiting approval!
### 🔍 The request is now under review by our team.

You can track the progress of your request here: [View Pull Request](https://github.com/TrdHuy/DezoneBuildPlugin/pull/19).

Thank you for your submission! 🚀

**Comment by TrdHuy** [comment]
## 🎉 **Request Approved!**
The permissions for **BalalaX** on the package **ArtWiz** have been successfully updated.

🔑 **API Key**: The API Key has been sent to your registered email address (**limjisu697@gmail.com**) along with detailed instructions on how to use it.


Thank you for your request! If you have further questions, feel free to contact our support team. 📧
