### ISSUE TITLE
[PBPR] Package Build Permission

### ISSUE THREAD

**Issue by Vuduchihi** [TrdHuy/DezoneOrgManager#17]
### 📧 Email Address

vuminhduc232323@gmail.com

### 📂 Select Package

ArtWiz

### ✍️ Reason for Request

I am responsible for maintaining the package. 
Please kindly approve for me.
Thank you!

**Comment by TrdHuy** [comment]
Hi @Vuduchihi, you need to be a member of the Dezone99 organization to have the required permissions. Please join the organization and re-open this issue once you have the necessary access.

**Comment by Vuduchihi** [comment]
I've joined the Dezone99 organization. 
Comment to re-open issue.
