### ISSUE TITLE
[PBPR] Package Build Permission

### ISSUE THREAD

**Issue by Vuduchihi** [TrdHuy/DezoneOrgManager#18]
### 📧 Email Address

vuminhduc232323@gmail.com

### 📂 Select Package

ArtWiz

### ✍️ Reason for Request

I am responsible for maintaining the package.
Please kindly approve for me.
Thank you!

*I don't have re-open issue permission so I create a new one.

**Comment by TrdHuy** [comment]
### ✅ Your request has been processed successfully and is awaiting approval!
### 🔍 The request is now under review by our team.

You can track the progress of your request here: [View Pull Request](https://github.com/TrdHuy/DezoneBuildPlugin/pull/21).

Thank you for your submission! 🚀

**Comment by TrdHuy** [comment]
## 🎉 **Request Approved!**
The permissions for **Vuduchihi** on the package **ArtWiz** have been successfully updated.

🔑 **API Key**: The API Key has been sent to your registered email address (**vuminhduc232323@gmail.com**) along with detailed instructions on how to use it.


Thank you for your request! If you have further questions, feel free to contact our support team. 📧
